//! FunctionalId enum -- 79 exchange-correlation functional identifiers
//! (78 from upstream + LB94 stub per Phase 5 D-16).
//!
//! Discriminant ordering matches `xcfun-master/src/functionals/list_of_functionals.hpp:18-95`
//! historical insertion order EXACTLY (CORE-07 + CORE-10) for ids 0..=77;
//! id 78 is `XC_LB94`, a Rust-only stub whose upstream `lb94.cpp` body is
//! `#if 0`'d (Phase 5 D-16). The `as u32` value indexes into the
//! `FUNCTIONAL_DESCRIPTORS` array generated by xtask regen-registry in
//! Plan 02-02 Wave-1A.

/// Unique identifier for each exchange-correlation functional.
#[allow(non_camel_case_types)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u32)]
pub enum FunctionalId {
    XC_SLATERX = 0,
    XC_PW86X = 1,
    XC_VWN3C = 2,
    XC_VWN5C = 3,
    XC_PBEC = 4,
    XC_PBEX = 5,
    XC_BECKEX = 6,
    XC_BECKECORRX = 7,
    XC_BECKESRX = 8,
    XC_BECKECAMX = 9,
    XC_BRX = 10,
    XC_BRC = 11,
    XC_BRXC = 12,
    XC_LDAERFX = 13,
    XC_LDAERFC = 14,
    XC_LDAERFC_JT = 15,
    XC_LYPC = 16,
    XC_OPTX = 17,
    XC_OPTXCORR = 18,
    XC_REVPBEX = 19,
    XC_RPBEX = 20,
    XC_SPBEC = 21,
    XC_VWN_PBEC = 22,
    XC_KTX = 23,
    XC_TFK = 24,
    XC_TW = 25,
    XC_PW91X = 26,
    XC_PW91K = 27,
    XC_PW92C = 28,
    XC_M05X = 29,
    XC_M05X2X = 30,
    XC_M06X = 31,
    XC_M06X2X = 32,
    XC_M06LX = 33,
    XC_M06HFX = 34,
    XC_M05X2C = 35,
    XC_M05C = 36,
    XC_M06C = 37,
    XC_M06HFC = 38,
    XC_M06LC = 39,
    XC_M06X2C = 40,
    XC_TPSSC = 41,
    XC_TPSSX = 42,
    XC_REVTPSSC = 43,
    XC_REVTPSSX = 44,
    XC_SCANC = 45,
    XC_SCANX = 46,
    XC_RSCANC = 47,
    XC_RSCANX = 48,
    XC_RPPSCANC = 49,
    XC_RPPSCANX = 50,
    XC_R2SCANC = 51,
    XC_R2SCANX = 52,
    XC_R4SCANC = 53,
    XC_R4SCANX = 54,
    XC_PZ81C = 55,
    XC_P86C = 56,
    XC_P86CORRC = 57,
    XC_BTK = 58,
    XC_VWK = 59,
    XC_B97X = 60,
    XC_B97C = 61,
    XC_B97_1X = 62,
    XC_B97_1C = 63,
    XC_B97_2X = 64,
    XC_B97_2C = 65,
    XC_CSC = 66,
    XC_APBEC = 67,
    XC_APBEX = 68,
    XC_ZVPBESOLC = 69,
    XC_BLOCX = 70,
    XC_PBEINTC = 71,
    XC_PBEINTX = 72,
    XC_PBELOCC = 73,
    XC_PBESOLX = 74,
    XC_TPSSLOCC = 75,
    XC_ZVPBEINTC = 76,
    XC_PW91C = 77,
    /// LB94 — Van Leeuwen-Baerends potential (1994).
    ///
    /// **D-16 (Phase 5 CONTEXT):** Descriptor present per D-16; the
    /// upstream `xcfun-master/src/functionals/lb94.cpp:15` is wrapped
    /// in `#if 0` ("Does not work and should maybe not be here in
    /// the first place"), so `Functional::eval` returns
    /// `XcError::Runtime` for this id. The descriptor exists so
    /// downstream tools can enumerate the name and so that
    /// `xcfun_set("lb94", 1.0)` succeeds at the FFI surface
    /// (failing only at eval time). LB94 is NOT counted in the
    /// upstream C++ enum (`list_of_functionals.hpp` does not list
    /// XC_LB94 — `XC_NR_FUNCTIONALS` stays at 78 in the C++ world);
    /// this discriminant is Rust-side only and does not collide
    /// with the C ABI numeric surface (the C ABI uses string
    /// names, not numeric ids).
    XC_LB94 = 78,
}

impl FunctionalId {
    /// Total number of functionals (78 upstream IDs + LB94 stub per Phase 5 D-16).
    /// Note: upstream C++ `XC_NR_FUNCTIONALS` stays at 78 (XC_LB94 absent there).
    pub const COUNT: usize = 79;

    /// Look up a functional by its string name (case-insensitive). Returns
    /// `None` if the name is not a known functional. Used by `Functional::set`
    /// (Plan 02-03 Wave-1B) and the C ABI `xcfun_set` (Phase 5 CAPI).
    pub fn from_name(name: &str) -> Option<Self> {
        // Match against the upper-case C identifier (with or without XC_ prefix).
        let upper = name.to_ascii_uppercase();
        let trimmed = upper.strip_prefix("XC_").unwrap_or(&upper);
        match trimmed {
            "SLATERX" => Some(Self::XC_SLATERX),
            "PW86X" => Some(Self::XC_PW86X),
            "VWN3C" => Some(Self::XC_VWN3C),
            "VWN5C" => Some(Self::XC_VWN5C),
            "PBEC" => Some(Self::XC_PBEC),
            "PBEX" => Some(Self::XC_PBEX),
            "BECKEX" => Some(Self::XC_BECKEX),
            "BECKECORRX" => Some(Self::XC_BECKECORRX),
            "BECKESRX" => Some(Self::XC_BECKESRX),
            "BECKECAMX" => Some(Self::XC_BECKECAMX),
            "BRX" => Some(Self::XC_BRX),
            "BRC" => Some(Self::XC_BRC),
            "BRXC" => Some(Self::XC_BRXC),
            "LDAERFX" => Some(Self::XC_LDAERFX),
            "LDAERFC" => Some(Self::XC_LDAERFC),
            "LDAERFC_JT" => Some(Self::XC_LDAERFC_JT),
            "LYPC" => Some(Self::XC_LYPC),
            "OPTX" => Some(Self::XC_OPTX),
            "OPTXCORR" => Some(Self::XC_OPTXCORR),
            "REVPBEX" => Some(Self::XC_REVPBEX),
            "RPBEX" => Some(Self::XC_RPBEX),
            "SPBEC" => Some(Self::XC_SPBEC),
            "VWN_PBEC" => Some(Self::XC_VWN_PBEC),
            "KTX" => Some(Self::XC_KTX),
            "TFK" => Some(Self::XC_TFK),
            "TW" => Some(Self::XC_TW),
            "PW91X" => Some(Self::XC_PW91X),
            "PW91K" => Some(Self::XC_PW91K),
            "PW92C" => Some(Self::XC_PW92C),
            "M05X" => Some(Self::XC_M05X),
            "M05X2X" => Some(Self::XC_M05X2X),
            "M06X" => Some(Self::XC_M06X),
            "M06X2X" => Some(Self::XC_M06X2X),
            "M06LX" => Some(Self::XC_M06LX),
            "M06HFX" => Some(Self::XC_M06HFX),
            "M05X2C" => Some(Self::XC_M05X2C),
            "M05C" => Some(Self::XC_M05C),
            "M06C" => Some(Self::XC_M06C),
            "M06HFC" => Some(Self::XC_M06HFC),
            "M06LC" => Some(Self::XC_M06LC),
            "M06X2C" => Some(Self::XC_M06X2C),
            "TPSSC" => Some(Self::XC_TPSSC),
            "TPSSX" => Some(Self::XC_TPSSX),
            "REVTPSSC" => Some(Self::XC_REVTPSSC),
            "REVTPSSX" => Some(Self::XC_REVTPSSX),
            "SCANC" => Some(Self::XC_SCANC),
            "SCANX" => Some(Self::XC_SCANX),
            "RSCANC" => Some(Self::XC_RSCANC),
            "RSCANX" => Some(Self::XC_RSCANX),
            "RPPSCANC" => Some(Self::XC_RPPSCANC),
            "RPPSCANX" => Some(Self::XC_RPPSCANX),
            "R2SCANC" => Some(Self::XC_R2SCANC),
            "R2SCANX" => Some(Self::XC_R2SCANX),
            "R4SCANC" => Some(Self::XC_R4SCANC),
            "R4SCANX" => Some(Self::XC_R4SCANX),
            "PZ81C" => Some(Self::XC_PZ81C),
            "P86C" => Some(Self::XC_P86C),
            "P86CORRC" => Some(Self::XC_P86CORRC),
            "BTK" => Some(Self::XC_BTK),
            "VWK" => Some(Self::XC_VWK),
            "B97X" => Some(Self::XC_B97X),
            "B97C" => Some(Self::XC_B97C),
            "B97_1X" => Some(Self::XC_B97_1X),
            "B97_1C" => Some(Self::XC_B97_1C),
            "B97_2X" => Some(Self::XC_B97_2X),
            "B97_2C" => Some(Self::XC_B97_2C),
            "CSC" => Some(Self::XC_CSC),
            "APBEC" => Some(Self::XC_APBEC),
            "APBEX" => Some(Self::XC_APBEX),
            "ZVPBESOLC" => Some(Self::XC_ZVPBESOLC),
            "BLOCX" => Some(Self::XC_BLOCX),
            "PBEINTC" => Some(Self::XC_PBEINTC),
            "PBEINTX" => Some(Self::XC_PBEINTX),
            "PBELOCC" => Some(Self::XC_PBELOCC),
            "PBESOLX" => Some(Self::XC_PBESOLX),
            "TPSSLOCC" => Some(Self::XC_TPSSLOCC),
            "ZVPBEINTC" => Some(Self::XC_ZVPBEINTC),
            "PW91C" => Some(Self::XC_PW91C),
            "LB94" => Some(Self::XC_LB94),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn count_is_79() {
        // Plan 05-00 D-16: upstream 78 + Rust-only XC_LB94 stub.
        assert_eq!(FunctionalId::COUNT, 79);
    }

    #[test]
    fn lb94_discriminant_is_78() {
        // Plan 05-00 D-16: XC_LB94 is the 79th id; appended after upstream
        // XC_PW91C (id 77). Note: upstream C++ list_of_functionals.hpp
        // does NOT contain XC_LB94 — its lb94.cpp is `#if 0`'d.
        assert_eq!(FunctionalId::XC_LB94 as u32, 78);
    }

    #[test]
    fn slaterx_discriminant_is_zero() {
        assert_eq!(FunctionalId::XC_SLATERX as u32, 0);
    }

    #[test]
    fn xcint_historical_ordering_lda_anchors() {
        // Anchors verified against xcfun-master/src/functionals/list_of_functionals.hpp.
        assert_eq!(FunctionalId::XC_SLATERX as u32, 0);
        assert_eq!(FunctionalId::XC_PW86X as u32, 1);
        assert_eq!(FunctionalId::XC_VWN3C as u32, 2);
        assert_eq!(FunctionalId::XC_VWN5C as u32, 3);
        assert_eq!(FunctionalId::XC_LDAERFX as u32, 13);
        assert_eq!(FunctionalId::XC_LDAERFC as u32, 14);
        assert_eq!(FunctionalId::XC_LDAERFC_JT as u32, 15);
        assert_eq!(FunctionalId::XC_TFK as u32, 24);
        assert_eq!(FunctionalId::XC_TW as u32, 25);
        assert_eq!(FunctionalId::XC_PW92C as u32, 28);
        assert_eq!(FunctionalId::XC_PZ81C as u32, 55);
        assert_eq!(FunctionalId::XC_VWK as u32, 59);
        assert_eq!(FunctionalId::XC_PW91C as u32, 77);
    }

    #[test]
    fn from_name_round_trip() {
        assert_eq!(FunctionalId::from_name("slaterx"), Some(FunctionalId::XC_SLATERX));
        assert_eq!(FunctionalId::from_name("XC_SLATERX"), Some(FunctionalId::XC_SLATERX));
        assert_eq!(FunctionalId::from_name("VWK"), Some(FunctionalId::XC_VWK));
        assert_eq!(FunctionalId::from_name("ldaerfc_jt"), Some(FunctionalId::XC_LDAERFC_JT));
        // Plan 05-00 D-16: LB94 lookup must succeed in all three case forms.
        assert_eq!(FunctionalId::from_name("lb94"), Some(FunctionalId::XC_LB94));
        assert_eq!(FunctionalId::from_name("LB94"), Some(FunctionalId::XC_LB94));
        assert_eq!(FunctionalId::from_name("XC_LB94"), Some(FunctionalId::XC_LB94));
        assert_eq!(FunctionalId::from_name("does_not_exist"), None);
    }
}
