//! Functional trait, Dependency bitflags, and TestData.

use crate::enums::{Mode, Vars};
use crate::functional_id::FunctionalId;

bitflags::bitflags! {
    /// Dependency flags indicating which input quantities a functional requires.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct Dependency: u32 {
        const DENSITY   = 0b0000_0001;
        const GRADIENT  = 0b0000_0010;
        const LAPLACIAN = 0b0000_0100;
        const KINETIC   = 0b0000_1000;
        const JP        = 0b0001_0000;
    }
}

/// Reference data for validating a functional implementation against xcfun C++.
///
/// **Scheduled for removal in Wave-0e** (D-04 + D-12: test data moves to
/// `FUNCTIONAL_DESCRIPTORS.test_in/test_out` generated by Plan 02-02 Wave-1A).
pub struct TestData {
    pub vars: Vars,
    pub mode: Mode,
    pub order: u32,
    pub threshold: f64,
    pub input: &'static [f64],
    pub expected_output: &'static [f64],
}

/// A single exchange-correlation energy functional.
///
/// **Scheduled for removal in Wave-0e** (D-04: functional surface moves to
/// `xcfun-eval`; `#[cube] fn <name>_kernel` replaces this trait entirely).
/// The `fn energy<T: Num>` method has been dropped already because Phase 1 D-09
/// retired the `Num` trait and Wave-0b deleted the `DensityVars<T>` host struct
/// this method depended on.
pub trait Functional: Send + Sync {
    /// Dependency flags indicating which input quantities this functional requires.
    fn depends(&self) -> Dependency;

    /// Unique identifier for this functional.
    fn id(&self) -> FunctionalId;

    /// Short human-readable description.
    fn description(&self) -> &'static str;

    /// Long description with references.
    fn long_description(&self) -> &'static str;

    /// Test data for accuracy validation.
    fn test_data(&self) -> TestData;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dependency_bits() {
        assert_eq!(Dependency::DENSITY.bits(), 1);
        assert_eq!(Dependency::GRADIENT.bits(), 2);
        assert_eq!(Dependency::LAPLACIAN.bits(), 4);
        assert_eq!(Dependency::KINETIC.bits(), 8);
        assert_eq!(Dependency::JP.bits(), 16);
    }

    #[test]
    fn dependency_bitwise_operations() {
        let combined = Dependency::DENSITY | Dependency::GRADIENT;
        assert!(combined.contains(Dependency::DENSITY));
        assert!(combined.contains(Dependency::GRADIENT));
        assert!(!combined.contains(Dependency::LAPLACIAN));
    }
}
