//! Registry tables — auto-generated by `xtask regen-registry`.
//!
//! See `xtask/src/bin/regen_registry.rs` + `xtask/assets/regen_registry/extractor.cpp`
//! for the generation pipeline. Each of the three sub-files carries a matching
//! `.sha256` stamp committed alongside; `cargo run -p xtask --bin regen-registry
//! -- --check` (QG-07 gate) fails if the committed sources drift from a fresh
//! regeneration.

mod generated {
    // Imports visible to every `include!`-d file below. The generated files
    // themselves carry no `use` lines; keeping imports in one place avoids
    // duplicate-import compile errors when three files share the same scope.
    use crate::enums::{Mode, Vars};
    use crate::functional_id::FunctionalId;
    use crate::traits::Dependency;

    // The three generated registry files are inlined via `include!` so each
    // can be a self-contained `.rs` emitted by the extractor without needing
    // its own `mod` header.
    include!("generated/FUNCTIONAL_DESCRIPTORS.rs");
    include!("generated/VARS_TABLE.rs");
    include!("generated/ALIASES.rs");
}

pub use self::generated::{
    ALIASES, Alias, FUNCTIONAL_DESCRIPTORS, FunctionalDescriptor, VARS_TABLE, VarsRow,
};
