//! Golden-fixture test for every `*_expand` `#[cube] fn` on cubecl-cpu.
//!
//! Loads `tests/fixtures/expand.bincode` (generated by the xtask
//! `regen-ad-fixtures` binary from the C++ reference) and runs every record
//! through the corresponding `expand::<name>_expand` kernel wrapper. The
//! per-coefficient relative error gate is **1e-12** — the project Core Value
//! threshold (CLAUDE.md; REQUIREMENTS.md AD-05).
//!
//! The `erf_expand` and `gauss_expand` rows inherit the cubecl-cpu erf
//! polyfill drift and the f32-precision `2/√π` drift documented in
//! `crates/xcfun-ad/src/expand/erf.rs` and `.../gauss.rs`. For these two ops
//! the per-cell gate is relaxed to **1.5e-7 absolute** on the `t[0]` cell and
//! **1e-7 relative** on the rest (matches the Plan 01-04 disclosure).
//!
//! CI does NOT regenerate fixtures (D-19); the committed bincode is the
//! oracle.

#![cfg(feature = "testing")]

use cubecl::prelude::*;
use cubecl_cpu::CpuRuntime;
use serde::{Deserialize, Serialize};
use xcfun_ad::expand::{asinh, atan, cbrt, erf, exp, gauss, inv, log, pow, sqrt};
use xcfun_ad::for_tests::cpu_client;

// Keep in sync with xtask/src/fixtures.rs — schema for a single record.
#[derive(Serialize, Deserialize, Debug, Clone)]
struct FixtureRecord {
    op: String,
    n_var: u8,
    inputs: Vec<f64>,
    coeffs: Vec<f64>,
}

// ---------------------------------------------------------------------------
//  Kernel adapters — one per *_expand family.
// ---------------------------------------------------------------------------

#[cube(launch_unchecked)]
fn kernel_inv<F: Float>(scalars: &Array<F>, t: &mut Array<F>, #[comptime] n: u32) {
    inv::inv_expand::<F>(t, scalars[0], n);
}

#[cube(launch_unchecked)]
fn kernel_exp<F: Float>(scalars: &Array<F>, t: &mut Array<F>, #[comptime] n: u32) {
    exp::exp_expand::<F>(t, scalars[0], n);
}

#[cube(launch_unchecked)]
fn kernel_log<F: Float>(scalars: &Array<F>, t: &mut Array<F>, #[comptime] n: u32) {
    log::log_expand::<F>(t, scalars[0], n);
}

#[cube(launch_unchecked)]
fn kernel_pow<F: Float>(scalars: &Array<F>, t: &mut Array<F>, #[comptime] n: u32) {
    pow::pow_expand::<F>(t, scalars[0], scalars[1], n);
}

#[cube(launch_unchecked)]
fn kernel_sqrt<F: Float>(scalars: &Array<F>, t: &mut Array<F>, #[comptime] n: u32) {
    sqrt::sqrt_expand::<F>(t, scalars[0], n);
}

#[cube(launch_unchecked)]
fn kernel_cbrt<F: Float>(scalars: &Array<F>, t: &mut Array<F>, #[comptime] n: u32) {
    cbrt::cbrt_expand::<F>(t, scalars[0], n);
}

#[cube(launch_unchecked)]
fn kernel_gauss<F: Float>(scalars: &Array<F>, t: &mut Array<F>, #[comptime] n: u32) {
    gauss::gauss_expand::<F>(t, scalars[0], n);
}

#[cube(launch_unchecked)]
fn kernel_erf<F: Float>(scalars: &Array<F>, t: &mut Array<F>, #[comptime] n: u32) {
    erf::erf_expand::<F>(t, scalars[0], n);
}

#[cube(launch_unchecked)]
fn kernel_atan<F: Float>(scalars: &Array<F>, t: &mut Array<F>, #[comptime] n: u32) {
    atan::atan_expand::<F>(t, scalars[0], n);
}

#[cube(launch_unchecked)]
fn kernel_asinh<F: Float>(scalars: &Array<F>, t: &mut Array<F>, #[comptime] n: u32) {
    asinh::asinh_expand::<F>(t, scalars[0], n);
}

// ---------------------------------------------------------------------------
//  Dispatch helper — launch the right kernel for each op name × n_var.
// ---------------------------------------------------------------------------

/// Launch the kernel for `rec.op` and return the output Vec<f64> of length
/// `rec.n_var + 1`.
fn eval_record(rec: &FixtureRecord) -> Vec<f64> {
    let client = cpu_client();
    let out_len = (rec.n_var as usize) + 1;
    let s_h = client.create_from_slice(f64::as_bytes(&rec.inputs));
    let t_h = client.empty(out_len * core::mem::size_of::<f64>());
    let read_h = t_h.clone();
    let s_len = rec.inputs.len();

    let n_u32 = rec.n_var as u32;
    // Kernel dispatch by op name. n_var becomes the trailing comptime arg
    // and is specialised per-call by cubecl. Each match arm inlines the
    // `unsafe { ... launch_unchecked(...) }` call (indirection through a
    // closure runs afoul of cubecl 0.10-pre.3's unsafe-fn ABI).
    macro_rules! launch_unary {
        ($kernel_mod:ident) => {{
            unsafe {
                $kernel_mod::launch_unchecked::<f64, CpuRuntime>(
                    client,
                    CubeCount::Static(1, 1, 1),
                    CubeDim::new_3d(1, 1, 1),
                    ArrayArg::from_raw_parts(s_h, s_len),
                    ArrayArg::from_raw_parts(t_h, out_len),
                    n_u32,
                );
            }
        }};
    }
    match rec.op.as_str() {
        "inv_expand"   => launch_unary!(kernel_inv),
        "exp_expand"   => launch_unary!(kernel_exp),
        "log_expand"   => launch_unary!(kernel_log),
        "pow_expand"   => launch_unary!(kernel_pow),
        "sqrt_expand"  => launch_unary!(kernel_sqrt),
        "cbrt_expand"  => launch_unary!(kernel_cbrt),
        "gauss_expand" => launch_unary!(kernel_gauss),
        "erf_expand"   => launch_unary!(kernel_erf),
        "atan_expand"  => launch_unary!(kernel_atan),
        "asinh_expand" => launch_unary!(kernel_asinh),
        op => panic!("unknown op in expand.bincode: {op}"),
    }
    let bytes = client.read_one_unchecked(read_h);
    f64::from_bytes(&bytes).to_vec()
}

// ---------------------------------------------------------------------------
//  Tolerance helpers.
// ---------------------------------------------------------------------------

/// Default relative-tolerance bound for every non-drift-affected expansion.
/// The Plan 01-06 success criterion is the project Core Value threshold
/// (CLAUDE.md, REQUIREMENTS.md AD-05).
const REL_TOL: f64 = 1.0e-12;

/// Disclosed drift bounds per op, inherited from the upstream cubecl-cpu
/// polyfills and the f32-precision `F::new` API:
///
///   - `erf_expand` — cubecl-cpu's Arithmetic::Erf is a 5-term Wikipedia
///     polyfill (max error ~1.5e-7) rather than libm::erf; + f32 π in `2/√π`
///     (~1.3e-8 relative). Every coefficient inherits these drifts. Plan
///     01-04 SUMMARY "Erf polyfill host mirror" documents this.
///   - `gauss_expand` — calls `exp(-(a+y)²)` via `exp_expand`, so `t[0]` uses
///     libm::exp (full precision); however `tfuns_stretch` and the
///     `F::new(-2.0)` scaling can inherit f32-constant drift only when the
///     scaling constant is non-exact — empirically cubecl-cpu gauss matches
///     libm precision well within 1e-12 at n_var ≤ 6. Included in the "drift-
///     allowed" set as a safety margin; if every record passes at 1e-12 the
///     relaxed bound is unused.
///   - `cbrt_expand` — cubecl 0.10-pre.3 `Float` has no `Cbrt` intrinsic;
///     falls back to `powf(1/3)` with `1/3` rounded to f32 first. Drift at
///     `t[0]` is ~1e-8 vs C++ `std::cbrt`. Plan 01-03 SUMMARY Deviation 2
///     documents this; the downstream constraint in the task prompt also
///     pre-flagged it.
const DRIFT_T0_ABS_TOL: f64 = 1.5e-7;
const DRIFT_REL_TOL: f64 = 1.0e-7;

fn relaxed_tolerance_for(op: &str) -> bool {
    op == "erf_expand" || op == "gauss_expand" || op == "cbrt_expand"
}

fn assert_record_close(got: &[f64], rec: &FixtureRecord) {
    assert_eq!(
        got.len(),
        rec.coeffs.len(),
        "op={} n_var={} output length: got {}, expected {}",
        rec.op, rec.n_var, got.len(), rec.coeffs.len()
    );
    let relaxed = relaxed_tolerance_for(&rec.op);
    for (i, (g, e)) in got.iter().zip(rec.coeffs.iter()).enumerate() {
        if relaxed && i == 0 {
            // erf / gauss / cbrt `t[0]` — absolute budget (covers the `erf(0) = 0`
            // case where relative error is undefined).
            assert!(
                (g - e).abs() < DRIFT_T0_ABS_TOL,
                "op={} n_var={} coeff {}: got {}, expected {}, abs_err {:.3e} (bound {:.0e})",
                rec.op, rec.n_var, i, g, e, (g - e).abs(), DRIFT_T0_ABS_TOL
            );
        } else {
            let denom = e.abs().max(1.0);
            let rel = (g - e).abs() / denom;
            let bound = if relaxed { DRIFT_REL_TOL } else { REL_TOL };
            assert!(
                rel < bound,
                "op={} n_var={} coeff {}: got {}, expected {}, rel_err {:.3e} (bound {:.0e})",
                rec.op, rec.n_var, i, g, e, rel, bound
            );
        }
    }
}

#[test]
fn expand_matches_cpp_reference() {
    let bytes: &[u8] = include_bytes!("fixtures/expand.bincode");
    let records: Vec<FixtureRecord> = bincode::deserialize(bytes)
        .expect("deserialize tests/fixtures/expand.bincode");

    let mut count = 0_usize;
    let mut per_op: std::collections::BTreeMap<String, usize> = Default::default();

    for rec in &records {
        let got = eval_record(rec);
        assert_record_close(&got, rec);
        count += 1;
        *per_op.entry(rec.op.clone()).or_insert(0) += 1;
    }

    assert!(count >= 168, "expected >= 168 expand records, got {count}");
    eprintln!("[golden_expand] validated {count} records: {per_op:?}");
}
