//! Golden-fixture test for the 9 composed `ctaylor_*` `#[cube] fn`s on
//! cubecl-cpu.
//!
//! Loads `tests/fixtures/composed.bincode` (generated by the xtask
//! `regen-ad-fixtures` binary from `ctaylor_math.hpp`) and runs every record
//! through the corresponding `xcfun_ad::math::ctaylor_*` kernel wrapper.
//! Per-coefficient tolerance is the project Core Value threshold **1e-12**
//! for most ops; the `ctaylor_erf` and `ctaylor_powi` (via `ctaylor_pow` for
//! negative exponents) inherit upstream drifts — see the `relaxed_tolerance_for`
//! helper and `crates/xcfun-ad/src/expand/erf.rs` for the precision
//! disclosure.
//!
//! CI does NOT regenerate fixtures (D-19); the committed bincode is the
//! oracle.

#![cfg(feature = "testing")]

use cubecl::prelude::*;
use cubecl_cpu::CpuRuntime;
use serde::{Deserialize, Serialize};
use xcfun_ad::for_tests::cpu_client;
use xcfun_ad::math;

// Keep in sync with xtask/src/fixtures.rs.
#[derive(Serialize, Deserialize, Debug, Clone)]
struct FixtureRecord {
    op: String,
    n_var: u8,
    inputs: Vec<f64>,
    coeffs: Vec<f64>,
}

// ---------------------------------------------------------------------------
//  Kernel adapters — one per composed fn. For `ctaylor_powi` we need a
//  separate adapter per exponent (the exponent is #[comptime] i32 and cannot
//  be passed as a runtime scalar).
// ---------------------------------------------------------------------------

#[cube(launch_unchecked)]
fn kernel_reciprocal<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_reciprocal::<F>(x, out, n);
}
#[cube(launch_unchecked)]
fn kernel_sqrt<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_sqrt::<F>(x, out, n);
}
#[cube(launch_unchecked)]
fn kernel_exp<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_exp::<F>(x, out, n);
}
#[cube(launch_unchecked)]
fn kernel_expm1<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_expm1::<F>(x, out, n);
}
#[cube(launch_unchecked)]
fn kernel_sqrtx_asinh_sqrtx<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_sqrtx_asinh_sqrtx::<F>(x, out, n);
}
#[cube(launch_unchecked)]
fn kernel_log<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_log::<F>(x, out, n);
}
#[cube(launch_unchecked)]
fn kernel_erf<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_erf::<F>(x, out, n);
}
#[cube(launch_unchecked)]
fn kernel_asinh<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_asinh::<F>(x, out, n);
}
#[cube(launch_unchecked)]
fn kernel_atan<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_atan::<F>(x, out, n);
}
#[cube(launch_unchecked)]
fn kernel_pow<F: Float>(
    x: &Array<F>,
    aa: &Array<F>,
    out: &mut Array<F>,
    #[comptime] n: u32,
) {
    math::ctaylor_pow::<F>(x, aa[0], out, n);
}

// Per-exponent `ctaylor_powi` launch adapters. Exponents ∈ {-2, -1, 0, 1, 2, 5, 10}
// match the fixture driver's emitted set.
#[cube(launch_unchecked)]
fn kernel_powi_neg2<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_powi_neg2::<F>(x, out, n);
}
#[cube(launch_unchecked)]
fn kernel_powi_neg1<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_powi_neg1::<F>(x, out, n);
}
#[cube(launch_unchecked)]
fn kernel_powi_0<F: Float>(out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_powi_0::<F>(out, n);
}
#[cube(launch_unchecked)]
fn kernel_powi_1<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_powi_1::<F>(x, out, n);
}
#[cube(launch_unchecked)]
fn kernel_powi_2<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_powi_2::<F>(x, out, n);
}
#[cube(launch_unchecked)]
fn kernel_powi_5<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_powi_5::<F>(x, out, n);
}
#[cube(launch_unchecked)]
fn kernel_powi_10<F: Float>(x: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    math::ctaylor_powi_10::<F>(x, out, n);
}

// ---------------------------------------------------------------------------
//  Dispatch by op name → correct kernel launch. Returns the kernel output.
// ---------------------------------------------------------------------------

fn eval_record(rec: &FixtureRecord) -> Vec<f64> {
    let client = cpu_client();
    let size = 1_usize << rec.n_var;
    let n_u32 = rec.n_var as u32;

    // For reciprocal/sqrt/exp/log/erf/asinh/atan the first `size` entries of
    // `inputs` are `x.c[..]`. For pow the last input entry is `a`. For powi
    // the last input entry is the integer exponent (encoded as f64).
    let x_slice = &rec.inputs[..size];
    let x_h = client.create_from_slice(f64::as_bytes(x_slice));
    let out_h = client.empty(size * core::mem::size_of::<f64>());
    let read_h = out_h.clone();

    // Simple unary kernels — reciprocal/sqrt/exp/log/erf/asinh/atan.
    macro_rules! launch_unary {
        ($kernel_mod:ident) => {{
            unsafe {
                $kernel_mod::launch_unchecked::<f64, CpuRuntime>(
                    client,
                    CubeCount::Static(1, 1, 1),
                    CubeDim::new_3d(1, 1, 1),
                    ArrayArg::from_raw_parts(x_h, size),
                    ArrayArg::from_raw_parts(out_h, size),
                    n_u32,
                );
            }
        }};
    }

    match rec.op.as_str() {
        "ctaylor_reciprocal" => launch_unary!(kernel_reciprocal),
        "ctaylor_sqrt" => launch_unary!(kernel_sqrt),
        "ctaylor_exp" => launch_unary!(kernel_exp),
        "ctaylor_expm1" => launch_unary!(kernel_expm1),
        "ctaylor_sqrtx_asinh_sqrtx" => launch_unary!(kernel_sqrtx_asinh_sqrtx),
        "ctaylor_log" => launch_unary!(kernel_log),
        "ctaylor_erf" => launch_unary!(kernel_erf),
        "ctaylor_asinh" => launch_unary!(kernel_asinh),
        "ctaylor_atan" => launch_unary!(kernel_atan),
        "ctaylor_pow" => {
            // inputs[..size] = x.c[..]; inputs[size] = a.
            let a = rec.inputs[size];
            let a_h = client.create_from_slice(f64::as_bytes(&[a]));
            unsafe {
                kernel_pow::launch_unchecked::<f64, CpuRuntime>(
                    client,
                    CubeCount::Static(1, 1, 1),
                    CubeDim::new_3d(1, 1, 1),
                    ArrayArg::from_raw_parts(x_h, size),
                    ArrayArg::from_raw_parts(a_h, 1),
                    ArrayArg::from_raw_parts(out_h, size),
                    n_u32,
                );
            }
        }
        "ctaylor_powi" => {
            // inputs[..size] = x.c[..]; inputs[size] = exponent as f64.
            let exponent = rec.inputs[size] as i32;
            match exponent {
                -2 => launch_unary!(kernel_powi_neg2),
                -1 => launch_unary!(kernel_powi_neg1),
                0 => {
                    // kernel_powi_0 doesn't take x.
                    unsafe {
                        kernel_powi_0::launch_unchecked::<f64, CpuRuntime>(
                            client,
                            CubeCount::Static(1, 1, 1),
                            CubeDim::new_3d(1, 1, 1),
                            ArrayArg::from_raw_parts(out_h, size),
                            n_u32,
                        );
                    }
                }
                1 => launch_unary!(kernel_powi_1),
                2 => launch_unary!(kernel_powi_2),
                5 => launch_unary!(kernel_powi_5),
                10 => launch_unary!(kernel_powi_10),
                other => panic!("unsupported powi exponent in fixture: {other}"),
            }
        }
        op => panic!("unknown op in composed.bincode: {op}"),
    }

    let bytes = client.read_one_unchecked(read_h);
    f64::from_bytes(&bytes).to_vec()
}

// ---------------------------------------------------------------------------
//  Tolerance policy.
// ---------------------------------------------------------------------------

const REL_TOL: f64 = 1.0e-12;

/// Drift budgets for ops that inherit upstream polyfill / f32-constant drift:
///
///   - `ctaylor_erf` — inherits `erf_expand`'s polyfill (Wikipedia 5-term,
///     max error ~1.5e-7) + `2/√π` f32 drift (~1.3e-8).
///   - `ctaylor_powi` with negative exponents — delegates to `ctaylor_pow`
///     which is exact in f64 operation path; kept at 1e-12 (not drift-
///     bounded).
///
/// Absolute t[0] budget covers `erf(0) = 0` where relative error is ill-defined.
const DRIFT_T0_ABS_TOL: f64 = 1.5e-7;
const DRIFT_REL_TOL: f64 = 1.0e-7;

fn relaxed_tolerance_for(op: &str) -> bool {
    op == "ctaylor_erf"
}

fn assert_record_close(got: &[f64], rec: &FixtureRecord) {
    assert_eq!(
        got.len(),
        rec.coeffs.len(),
        "op={} n_var={} output length: got {}, expected {}",
        rec.op, rec.n_var, got.len(), rec.coeffs.len()
    );
    let relaxed = relaxed_tolerance_for(&rec.op);
    for (i, (g, e)) in got.iter().zip(rec.coeffs.iter()).enumerate() {
        if relaxed && i == 0 {
            assert!(
                (g - e).abs() < DRIFT_T0_ABS_TOL,
                "op={} n_var={} coeff {}: got {}, expected {}, abs_err {:.3e} (bound {:.0e})",
                rec.op, rec.n_var, i, g, e, (g - e).abs(), DRIFT_T0_ABS_TOL
            );
        } else {
            let denom = e.abs().max(1.0);
            let rel = (g - e).abs() / denom;
            let bound = if relaxed { DRIFT_REL_TOL } else { REL_TOL };
            assert!(
                rel < bound,
                "op={} n_var={} coeff {}: got {}, expected {}, rel_err {:.3e} (bound {:.0e})",
                rec.op, rec.n_var, i, g, e, rel, bound
            );
        }
    }
}

#[test]
fn composed_matches_cpp_reference() {
    let bytes: &[u8] = include_bytes!("fixtures/composed.bincode");
    let records: Vec<FixtureRecord> = bincode::deserialize(bytes)
        .expect("deserialize tests/fixtures/composed.bincode");

    let mut count = 0_usize;
    let mut per_op: std::collections::BTreeMap<String, usize> = Default::default();

    for rec in &records {
        let got = eval_record(rec);
        assert_record_close(&got, rec);
        count += 1;
        *per_op.entry(rec.op.clone()).or_insert(0) += 1;
    }

    assert!(count >= 96, "expected >= 96 composed records, got {count}");
    eprintln!("[golden_composed] validated {count} records: {per_op:?}");
}

/// Plan 03-00 Task 4 — dedicated ctaylor_expm1 fixture-gate.
#[test]
fn test_ctaylor_expm1() {
    let bytes: &[u8] = include_bytes!("fixtures/composed.bincode");
    let records: Vec<FixtureRecord> = bincode::deserialize(bytes)
        .expect("deserialize tests/fixtures/composed.bincode");

    let mut count = 0_usize;
    for rec in records.iter().filter(|r| r.op == "ctaylor_expm1") {
        let got = eval_record(rec);
        assert_record_close(&got, rec);
        count += 1;
    }
    assert!(count >= 2000, "expected >= 2000 ctaylor_expm1 records, got {count}");
    eprintln!("[golden_composed::test_ctaylor_expm1] validated {count} records");
}

/// Plan 03-00 Task 4 — dedicated ctaylor_sqrtx_asinh_sqrtx fixture-gate.
///
/// Exercises BOTH branches of the D-06 port: |x0| >= 0.5 (direct
/// composition) AND |x0| < 0.5 (unconditional [8,8] Padé). Fixture
/// strata are generated in `xtask/assets/regen_ad_fixtures/driver.cpp`
/// with seed `0xb16b00b5` across x0 in [1e-10, 100].
#[test]
fn test_sqrtx_asinh_sqrtx() {
    let bytes: &[u8] = include_bytes!("fixtures/composed.bincode");
    let records: Vec<FixtureRecord> = bincode::deserialize(bytes)
        .expect("deserialize tests/fixtures/composed.bincode");

    let mut count = 0_usize;
    for rec in records.iter().filter(|r| r.op == "ctaylor_sqrtx_asinh_sqrtx") {
        let got = eval_record(rec);
        assert_record_close(&got, rec);
        count += 1;
    }
    assert!(count >= 2000, "expected >= 2000 ctaylor_sqrtx_asinh_sqrtx records, got {count}");
    eprintln!("[golden_composed::test_sqrtx_asinh_sqrtx] validated {count} records");
}
