//! Golden test for `ctaylor_br_inverse` on cubecl-cpu.
//!
//! Per Phase 4 plan 04-00 Task 1 acceptance criteria, this test verifies:
//!
//! 1. The host-side scalar `br_scalar` function converges and inverts
//!    `BR_z` to within rel-tolerance 1e-13 on a representative set of
//!    z-values across all four C++ initial-guess branches (covered by
//!    inline `#[cfg(test)] mod tests` in `expand/br_inverse.rs`).
//! 2. `ctaylor_br_inverse` (host-seeded `out[CNST]` + cubecl-driven
//!    linear-method polynomial sweep) compiles, launches without panic,
//!    and produces finite output at N ∈ {2, 3} on a small set of
//!    representative z-values.
//!
//! **Tier 1 (smoke + finiteness)** — strict 1e-12 vs C++ `BR_taylor` is
//! enabled when full bincode fixtures generated by an extended
//! `xtask regen-ad-fixtures` driver are available. The fixture-gate work
//! is deferred to Wave 1 (Plan 04-01) where the BR family kernels first
//! consume `ctaylor_br_inverse`; until then this test acts as a structural
//! guard verifying the primitive runs end-to-end.

#![cfg(feature = "testing")]

use cubecl::prelude::*;
use cubecl_cpu::CpuRuntime;
use xcfun_ad::br_scalar;
use xcfun_ad::ctaylor_br_inverse;
use xcfun_ad::for_tests::cpu_client;

/// Kernel adapter — wraps `ctaylor_br_inverse` so the host launcher can
/// thread the comptime `n` through.
#[cube(launch_unchecked)]
fn kernel_br_inverse<F: Float>(
    z: &Array<F>,
    out: &mut Array<F>,
    #[comptime] n: u32,
) {
    ctaylor_br_inverse::<F>(z, out, n);
}

/// Launch `ctaylor_br_inverse` on a CTaylor<f64, n_var> seeded with
/// `z[0] = z0`, `z[1] = 1.0` (VAR0 slope), zeros elsewhere. The host
/// pre-seeds `out[0] = br_scalar(z0)`. Returns the output coefficient
/// array (length `1 << n_var`).
fn run_br_inverse(z0: f64, n_var: u32) -> Vec<f64> {
    let client = cpu_client();
    let size = 1_usize << n_var;

    // Seed input z = (z0 + 1·VAR0) — the standard CTaylor<f64, 1> shape;
    // higher slots zero.
    let mut z_in = vec![0.0_f64; size];
    z_in[0] = z0;
    if size > 1 {
        z_in[1] = 1.0;
    }

    // Seed out[0] = br_scalar(z0); higher slots are zero (ctaylor_br_inverse
    // body fills them via the linear-method sweep).
    let mut out_in = vec![0.0_f64; size];
    out_in[0] = br_scalar(z0);

    let z_h = client.create_from_slice(f64::as_bytes(&z_in));
    let out_h = client.create_from_slice(f64::as_bytes(&out_in));
    let read_h = out_h.clone();

    unsafe {
        kernel_br_inverse::launch_unchecked::<f64, CpuRuntime>(
            client,
            CubeCount::Static(1, 1, 1),
            CubeDim::new_3d(1, 1, 1),
            ArrayArg::from_raw_parts(z_h, size),
            ArrayArg::from_raw_parts(out_h, size),
            n_var,
        );
    }

    let bytes = client.read_one_unchecked(read_h);
    f64::from_bytes(&bytes).to_vec()
}

/// `ctaylor_br_inverse` produces finite output at N=2 across all four
/// C++ initial-guess branches.
#[test]
fn ctaylor_br_inverse_runs_n2() {
    let zs: [f64; 4] = [-1e6, -10.0, 0.5, 5.0];
    for &z0 in &zs {
        let out = run_br_inverse(z0, 2);
        assert_eq!(out.len(), 4);
        for (i, &v) in out.iter().enumerate() {
            assert!(
                v.is_finite(),
                "z0={} N=2: out[{}] = {} is non-finite",
                z0,
                i,
                v
            );
        }
        // Slot 0 must equal br_scalar(z0) (host-seeded; body preserves CNST).
        assert_eq!(
            out[0],
            br_scalar(z0),
            "z0={}: out[0] mismatch (host seed should survive)",
            z0
        );
    }
}

/// `ctaylor_br_inverse` produces finite output at N=3.
#[test]
fn ctaylor_br_inverse_runs_n3() {
    let zs: [f64; 4] = [-1e6, -10.0, 0.5, 5.0];
    for &z0 in &zs {
        let out = run_br_inverse(z0, 3);
        assert_eq!(out.len(), 8);
        for (i, &v) in out.iter().enumerate() {
            assert!(
                v.is_finite(),
                "z0={} N=3: out[{}] = {} is non-finite",
                z0,
                i,
                v
            );
        }
        assert_eq!(out[0], br_scalar(z0));
    }
}

/// `ctaylor_br_inverse` at N=1 (single VAR0 slot only) — the inverse-
/// function-theorem first-derivative coefficient `out[1] = 1 / BR_z'(x0)`
/// where `x0 = br_scalar(z0)`.
///
/// Mathematically, with `BR_z(x) = (1 - 2/x) · exp(2x/3)`:
/// `BR_z'(x) = (+2/x²) · exp(2x/3) + (1 - 2/x) · (2/3) · exp(2x/3)`
///           `= exp(2x/3) · [2/x² + (2/3)(1 - 2/x)]`
///           `= exp(2x/3) · [2/x² + (2/3) - 4/(3x)]`
///
/// We verify `out[1] · BR_z'(out[0]) ≈ 1` to rel-tolerance 1e-12.
#[test]
fn ctaylor_br_inverse_first_derivative_at_n1() {
    let zs: [f64; 4] = [-100.0, -1.5, 0.5, 5.0];
    for &z0 in &zs {
        let out = run_br_inverse(z0, 1);
        let x0 = out[0];
        let inv_dz_dx = out[1];

        // BR_z'(x) = exp(2x/3) · [2/x² + 2/3 - 4/(3x)]
        let exp_arg = (2.0_f64 / 3.0_f64) * x0;
        let bracket =
            2.0 / (x0 * x0) + 2.0 / 3.0 - 4.0 / (3.0 * x0);
        let dz_dx = exp_arg.exp() * bracket;

        let product = inv_dz_dx * dz_dx;
        let rel = (product - 1.0).abs();
        assert!(
            rel < 1e-12,
            "z0={}: x0={}, out[1]={}, BR_z'(x0)={}, product={}, rel={:.3e}",
            z0,
            x0,
            inv_dz_dx,
            dz_dx,
            product,
            rel
        );
    }
}
