//! Golden-fixture test for `ctaylor_mul` on cubecl-cpu.
//!
//! Loads `tests/fixtures/mul.bincode` (generated by
//! `cargo run -p xtask --bin regen-ad-fixtures`) and runs every record
//! through the cubecl `ctaylor_mul` kernel.
//!
//! For `n_var ∈ 0..=3` (AD-05's bit-exact gate): asserts
//! `f64::to_bits` identity with the C++ reference coefficients.
//!
//! For `n_var = 4`: asserts relative error ≤ 1e-13 (not bit-exact; libm
//! drift between C++ and cubecl-cpu permitted at the larger N).
//!
//! CI does NOT regenerate fixtures — the committed bincode + JSON manifest
//! are the oracle (D-19). Drift between the vendored C++ sources and the
//! fixtures is detected via the manifest's sha256 hash.
//!
//! Schema duplication: `FixtureRecord` below is kept in sync with
//! `xtask/src/fixtures.rs`. We duplicate rather than take a path-dep on
//! `xtask` to keep the `xcfun-ad` dev-dep graph narrow.

#![cfg(feature = "testing")]

use cubecl::prelude::*;
use cubecl_cpu::CpuRuntime;
use serde::{Deserialize, Serialize};
use xcfun_ad::ctaylor_rec::mul::ctaylor_mul;
use xcfun_ad::for_tests::cpu_client;

// Keep in sync with xtask/src/fixtures.rs — schema for a single record.
#[derive(Serialize, Deserialize, Debug, Clone)]
struct FixtureRecord {
    op: String,
    n_var: u8,
    inputs: Vec<f64>,
    coeffs: Vec<f64>,
}

// Kernel adapter — delegates to xcfun_ad::ctaylor_rec::mul::ctaylor_mul and
// threads the comptime `n` through. Matches the pattern from
// `tests/ctaylor_unit.rs`.
#[cube(launch_unchecked)]
fn kernel_mul<F: Float>(a: &Array<F>, b: &Array<F>, out: &mut Array<F>, #[comptime] n: u32) {
    ctaylor_mul::<F>(a, b, out, n);
}

/// Launch one `ctaylor_mul` record on cubecl-cpu and return the output
/// `Vec<f64>` (length `1 << n_var`).
fn run_mul_record(rec: &FixtureRecord) -> Vec<f64> {
    let client = cpu_client();
    let size = 1_usize << rec.n_var;
    assert_eq!(
        rec.inputs.len(),
        2 * size,
        "mul fixture inputs: expected {} entries (2 × 2^{}), got {}",
        2 * size,
        rec.n_var,
        rec.inputs.len()
    );

    let a = &rec.inputs[..size];
    let b = &rec.inputs[size..2 * size];

    let a_h = client.create_from_slice(f64::as_bytes(a));
    let b_h = client.create_from_slice(f64::as_bytes(b));
    let out_h = client.empty(size * core::mem::size_of::<f64>());
    let read_h = out_h.clone();

    unsafe {
        kernel_mul::launch_unchecked::<f64, CpuRuntime>(
            client,
            CubeCount::Static(1, 1, 1),
            CubeDim::new_3d(1, 1, 1),
            ArrayArg::from_raw_parts(a_h, size),
            ArrayArg::from_raw_parts(b_h, size),
            ArrayArg::from_raw_parts(out_h, size),
            rec.n_var as u32,
        );
    }

    let bytes = client.read_one_unchecked(read_h);
    f64::from_bytes(&bytes).to_vec()
}

#[test]
fn ctaylor_mul_matches_cpp_reference() {
    let bytes: &[u8] = include_bytes!("fixtures/mul.bincode");
    let records: Vec<FixtureRecord> =
        bincode::deserialize(bytes).expect("deserialize tests/fixtures/mul.bincode");

    let mut bit_exact_count = 0_usize;
    let mut rel_err_count = 0_usize;
    // Per-N pass counters for the SUMMARY.md "per-n_var pass rate" line.
    let mut per_n_pass = [0_usize; 5]; // n_var ∈ {0..=4}
    let mut per_n_total = [0_usize; 5];

    for rec in records.iter().filter(|r| r.op == "mul") {
        let n_idx = rec.n_var as usize;
        assert!(n_idx <= 4, "unexpected n_var {} in mul fixtures", rec.n_var);
        per_n_total[n_idx] += 1;

        let got = run_mul_record(rec);
        assert_eq!(
            got.len(),
            rec.coeffs.len(),
            "mul n_var={} output length: got {}, expected {}",
            rec.n_var,
            got.len(),
            rec.coeffs.len()
        );

        if rec.n_var <= 3 {
            // AD-05: f64::to_bits identity for n_var ∈ 0..=3.
            for (i, (g, e)) in got.iter().zip(rec.coeffs.iter()).enumerate() {
                assert_eq!(
                    g.to_bits(),
                    e.to_bits(),
                    "mul n_var={} coeff {}: got {} ({:#x}), expected {} ({:#x})",
                    rec.n_var,
                    i,
                    g,
                    g.to_bits(),
                    e,
                    e.to_bits(),
                );
            }
            bit_exact_count += 1;
            per_n_pass[n_idx] += 1;
        } else {
            // n_var = 4: relative-error gate (≤ 1e-13).
            for (i, (g, e)) in got.iter().zip(rec.coeffs.iter()).enumerate() {
                let denom = e.abs().max(1.0);
                let rel = (g - e).abs() / denom;
                assert!(
                    rel < 1e-13,
                    "mul n_var={} coeff {}: got {}, expected {}, rel_err {:.3e}",
                    rec.n_var,
                    i,
                    g,
                    e,
                    rel,
                );
            }
            rel_err_count += 1;
            per_n_pass[n_idx] += 1;
        }
    }

    // Smoke-check counts: 50 seeds × 4 bit-exact N (n_var 0..=3) = 200;
    //                    50 seeds × 1 rel-err N (n_var = 4)     = 50.
    assert!(
        bit_exact_count >= 200,
        "expected ≥ 200 bit-exact records, got {}",
        bit_exact_count
    );
    assert!(
        rel_err_count >= 50,
        "expected ≥ 50 rel-err records, got {}",
        rel_err_count
    );

    eprintln!(
        "[golden_mul] per-n pass: n=0 {}/{}, n=1 {}/{}, n=2 {}/{}, n=3 {}/{}, n=4 {}/{}",
        per_n_pass[0],
        per_n_total[0],
        per_n_pass[1],
        per_n_total[1],
        per_n_pass[2],
        per_n_total[2],
        per_n_pass[3],
        per_n_total[3],
        per_n_pass[4],
        per_n_total[4],
    );
}
