"""1e-12 cross-language parity gate.

Loads `tests/fixtures/eval_parity.json` (generated by
`cargo run -p xcfun-py --release --example gen_py_fixtures`) and asserts
that `Functional.eval_vec` reproduces the Rust facade's `Functional::eval`
output to 1e-12 relative tolerance.

The fixture file is committed; regenerate it whenever the Rust facade
changes. The Phase 5 D-08-A bit-pattern is the source of truth for the
rtol value.
"""
import json
import pathlib

import numpy as np
import pytest
import xcfun_rs as xc


FIXTURE_PATH = pathlib.Path(__file__).parent / "fixtures" / "eval_parity.json"


@pytest.fixture(scope="module")
def fixtures():
    if not FIXTURE_PATH.exists():
        pytest.skip(
            f"{FIXTURE_PATH} not present - run "
            "`cargo run -p xcfun-py --release --example gen_py_fixtures` "
            "to regenerate."
        )
    return json.loads(FIXTURE_PATH.read_text())


def test_parity_fixture_corpus_size(fixtures):
    # Lock the corpus size; if the example produces fewer than 8 fixtures
    # something has regressed.
    assert len(fixtures) >= 8


def test_parity_each_fixture_within_1e_minus_12(fixtures):
    for fx in fixtures:
        f = xc.Functional(
            fx["functional"],
            vars=xc.Vars(fx["vars"]),
            mode=xc.Mode(fx["mode"]),
            order=fx["order"],
        )
        density = np.asarray(fx["density"], dtype=np.float64).reshape(1, -1)
        out = f.eval_vec(density)
        # out is shape (1, outlen); fx["expected"] is the per-point output.
        np.testing.assert_allclose(
            out[0],
            np.asarray(fx["expected"], dtype=np.float64),
            rtol=1e-12,
            err_msg=(
                f"functional={fx['functional']} vars={fx['vars']} "
                f"mode={fx['mode']} order={fx['order']}"
            ),
        )
