"""Type stubs for xcfun_rs (PEP 561). Phase 7 Plan 07-02 surface = 11 free fns."""
from typing import Optional

def version() -> str: ...
def splash() -> str: ...
def authors() -> str: ...
def is_compatible_library() -> bool: ...
def self_test() -> int: ...
def which_vars(
    func_type: int,
    dens_type: int,
    laplacian: int,
    kinetic: int,
    current: int,
    explicit_derivatives: int,
) -> Optional[int]: ...
def which_mode(mode_type: int) -> Optional[int]: ...
def enumerate_parameters(p: int) -> Optional[str]: ...
def enumerate_aliases(n: int) -> Optional[str]: ...
def describe_short(name: str) -> Optional[str]: ...
def describe_long(name: str) -> Optional[str]: ...

# Phase 7 Plan 07-03 — XcfunError stub.

class XcfunError(Exception):
    code: int
    kind: str
    def __init__(self, *args: object) -> None: ...

__version__: str
