//! `validation/build.rs` — compiles the xcfun-master C++ reference sources
//! (XCFunctional.cpp + xcint.cpp + 11 Phase-2 LDA .cpp + common_parameters.cpp
//! + aliases.cpp) plus the auto-generated `c_stubs.cpp` (67 non-LDA stubs,
//! emitted by `xtask regen-registry`) into the static lib `xcfun_cpp_lda`.
//!
//! Flags:
//!   -std=c++17                     — xcfun-master requires C++17.
//!   -fno-fast-math -ffp-contract=off — algorithmic-identity parity with
//!                                    Rust side (CLAUDE.md accuracy gate).
//!   -DXCFUN_MAX_ORDER=6            — macro expansion scope for FOR_EACH.
//!
//! Include paths mirror `xcfun-master/src/CMakeLists.txt`. The stock xcfun
//! CMake build `configure_file`s `api/xcfun.h` into
//! `$BUILDDIR/include/XCFun/xcfun.h` and auto-generates `XCFunExport.h`
//! (via CMake's `GenerateExportHeader`). We reproduce both in `$OUT_DIR`
//! so `#include "XCFun/xcfun.h"` and `#include "XCFun/XCFunExport.h"`
//! resolve without a full CMake build.

use std::fs;
use std::path::PathBuf;

fn main() -> std::io::Result<()> {
    let xcfun_root = "../xcfun-master";
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR unset"));
    let shim_include = out_dir.join("include");
    let xcfun_subdir = shim_include.join("XCFun");
    fs::create_dir_all(&xcfun_subdir)?;

    // Copy api/xcfun.h → $OUT_DIR/include/XCFun/xcfun.h (matches CMake
    // configure_file(... COPYONLY) step in xcfun-master/api/CMakeLists.txt).
    fs::copy(
        format!("{}/api/xcfun.h", xcfun_root),
        xcfun_subdir.join("xcfun.h"),
    )?;

    // Generate a minimal XCFunExport.h. We build xcfun as a STATIC lib (cc::Build
    // default), so all symbols are effectively local; the macros can expand to
    // nothing (or plain `extern "C"` semantics from xcfun.h itself). Mirrors
    // the output of CMake's GenerateExportHeader for a non-shared target.
    let export_header = r#"/* Auto-generated by validation/build.rs — mirrors CMake
 * GenerateExportHeader for a STATIC xcfun build. No visibility attributes
 * are needed because every symbol is statically linked into the validation
 * binary; the macros expand to nothing. */
#ifndef XCFUN_EXPORT_H
#define XCFUN_EXPORT_H

#ifdef __cplusplus
#  define XCFUN_EXPORT
#  define XCFUN_NO_EXPORT
#  define XCFUN_DEPRECATED
#  define XCFUN_DEPRECATED_EXPORT
#  define XCFUN_DEPRECATED_NO_EXPORT
#else
#  define XCFUN_EXPORT
#  define XCFUN_NO_EXPORT
#  define XCFUN_DEPRECATED
#  define XCFUN_DEPRECATED_EXPORT
#  define XCFUN_DEPRECATED_NO_EXPORT
#endif

#ifndef XCFUN_NO_DEPRECATED
#  define XCFUN_NO_DEPRECATED
#endif

#endif /* XCFUN_EXPORT_H */
"#;
    fs::write(xcfun_subdir.join("XCFunExport.h"), export_header)?;

    let mut build = cc::Build::new();
    build
        .cpp(true)
        .std("c++17")
        .flag_if_supported("-fno-fast-math")
        .flag_if_supported("-ffp-contract=off")
        .define("XCFUN_MAX_ORDER", "6")
        // $OUT_DIR/include — resolves `#include "XCFun/xcfun.h"` and `XCFunExport.h`.
        .include(&shim_include)
        .include(format!("{}/api", xcfun_root))
        .include(format!("{}/src", xcfun_root))
        .include(format!("{}/src/functionals", xcfun_root))
        .include(format!("{}/external/upstream/taylor", xcfun_root))
        .file(format!("{}/src/XCFunctional.cpp", xcfun_root))
        .file(format!("{}/src/xcint.cpp", xcfun_root))
        .file(format!("{}/src/functionals/aliases.cpp", xcfun_root))
        .file(format!("{}/src/functionals/common_parameters.cpp", xcfun_root));

    // 11 Phase-2 LDA functional .cpp files. File stems match the xcfun-master
    // layout (vwn3.cpp contains XC_VWN3C; vonw.cpp contains XC_VWK).
    for f in &[
        "slaterx",
        "vwn3",
        "vwn5c",
        "pw92c",
        "pz81c",
        "ldaerfx",
        "ldaerfc",
        "ldaerfc_jt",
        "tfk",
        "tw",
        "vonw",
    ] {
        build.file(format!("{}/src/functionals/{}.cpp", xcfun_root, f));
    }

    // Phase 3 plan 03-02 — 14 GGA-family .cpp files (12 PBE + 1 Becke 4-in-1
    // file `beckex.cpp` carrying BECKEX/BECKECORRX/BECKESRX/BECKECAMX + 1 LYP).
    for f in &[
        // PBE family — 12 functionals across 12 .cpp files.
        "pbex",
        "pbec",
        "revpbex",
        "rpbex",
        "pbesolx",
        "pbeintx",
        "pbeintc",
        "spbec",
        "pbelocc",
        "zvpbesolc",
        "zvpbeint", // file is `zvpbeint.cpp`, defines XC_ZVPBEINTC
        // VWN_PBEC is also in pbec.cpp (XC_VWN_PBEC second FUNCTIONAL macro).
        // Becke family — single-file 4-in-1.
        "beckex",
        // LYP.
        "lypc",
    ] {
        build.file(format!("{}/src/functionals/{}.cpp", xcfun_root, f));
    }

    // Phase 3 plan 03-03 — 9 GGA-family .cpp files for 10 Wave-3 functionals.
    // p86c.cpp contains both XC_P86C and XC_P86CORRC (2 FUNCTIONAL macros).
    for f in &[
        "optx",     // XC_OPTX (id=17)
        "optxcorr", // XC_OPTXCORR (id=18)
        "pw86x",    // XC_PW86X (id=1)
        "pw91x",    // XC_PW91X (id=26)
        "pw91c",    // XC_PW91C (id=77)
        "pw91k",    // XC_PW91K (id=27)
        "p86c",     // XC_P86C (id=56) + XC_P86CORRC (id=57)
        "apbex",    // XC_APBEX (id=68)
        "apbec",    // XC_APBEC (id=67)
    ] {
        build.file(format!("{}/src/functionals/{}.cpp", xcfun_root, f));
    }

    // Phase 3 plan 03-04 — 5 GGA-family .cpp files for 8 Wave-4 functionals.
    // b97xc.cpp ships XC_B97X + XC_B97C; b97-1xc.cpp ships XC_B97_1X + XC_B97_1C;
    // b97-2xc.cpp ships XC_B97_2X + XC_B97_2C; ktx.cpp ships XC_KTX; btk.cpp ships XC_BTK.
    for f in &[
        "b97xc",   // XC_B97X (60) + XC_B97C (61)
        "b97-1xc", // XC_B97_1X (62) + XC_B97_1C (63)
        "b97-2xc", // XC_B97_2X (64) + XC_B97_2C (65)
        "ktx",     // XC_KTX (23)
        "btk",     // XC_BTK (58)
    ] {
        build.file(format!("{}/src/functionals/{}.cpp", xcfun_root, f));
    }

    // 67 non-LDA stubs auto-generated by `xtask regen-registry` (Wave-2-1).
    build.file("c_stubs.cpp");

    println!("cargo:rerun-if-changed={}/src", xcfun_root);
    println!("cargo:rerun-if-changed={}/api/xcfun.h", xcfun_root);
    println!("cargo:rerun-if-changed=c_stubs.cpp");
    println!("cargo:rerun-if-changed=build.rs");

    build.compile("xcfun_cpp_lda");
    Ok(())
}
