// validation/c_stubs.cpp — AUTO-GENERATED by xtask regen-registry. DO NOT EDIT.
// Stubs for cc-compile — every non-LDA functional ID needs a fundat_db
// specialisation or xcint.cpp template recursion fails to link.
//
// Phase 3 plan 03-02 removes 17 GGA stubs (PBE×12 + Becke×4 + LYP×1).
// Phase 3 plan 03-03 removes 10 more stubs (OPTX×2 + PW86/91×4 + P86×2 + APBE×2).
// Phase 3 plan 03-04 removes 8 more stubs (B97×6 + KTX + BTK).
// Phase 4 plan 04-01 Wave 1 removes 5 metaGGA stubs (TPSS×3 + revTPSS×2).
// Stubs remaining: 67 - 17 - 10 - 8 - 5 = 27.

#include "functional.hpp"

template <typename num> static num stub_unimpl(const densvars<num> &) { return num(0); }

FUNCTIONAL(XC_BRX) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_LAPLACIAN|XC_KINETIC|XC_JP, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_BRC) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_LAPLACIAN|XC_KINETIC|XC_JP, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_BRXC) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_LAPLACIAN|XC_KINETIC|XC_JP, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M05X) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M05X2X) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06X) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06X2X) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06LX) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06HFX) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M05X2C) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M05C) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06C) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06HFC) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06LC) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06X2C) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_SCANC) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_SCANX) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_RSCANC) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_RSCANX) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_RPPSCANC) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_RPPSCANX) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_R2SCANC) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_R2SCANX) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_R4SCANC) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_R4SCANX) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_CSC) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_LAPLACIAN|XC_KINETIC|XC_JP, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_BLOCX) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
