// validation/c_stubs.cpp — AUTO-GENERATED by xtask regen-registry. DO NOT EDIT.
// Stubs for cc-compile — every non-LDA functional ID needs a fundat_db
// specialisation or xcint.cpp template recursion fails to link.
//
// Phase 3 plan 03-02 removes 17 GGA stubs (PBE×12 + Becke×4 + LYP×1).
// Phase 3 plan 03-03 removes 10 more stubs (OPTX×2 + PW86/91×4 + P86×2 + APBE×2).
// Phase 3 plan 03-04 removes 8 more stubs (B97×6 + KTX + BTK).
// Phase 4 plan 04-01 Wave 1 removes 5 metaGGA stubs (TPSS×3 + revTPSS×2).
// Phase 4 plan 04-01 Task 2 removes 4 more stubs (BRX + BRC + BRXC + CSC).
// Phase 4 plan 04-02 removes 10 SCAN-family stubs (SCAN×2 + rSCAN×2 + r++SCAN×2 + r2SCAN×2 + r4SCAN×2).
// Phase 4 plan 04-03 removes 13 more stubs (M05×4 + M06×8 + BLOCX).
// Stubs remaining: 67 - 17 - 10 - 8 - 5 - 4 - 10 - 13 = 0.
//
// All non-LDA functionals now have native ports compiled into the validation
// harness. This file is intentionally empty (apart from the include) so the
// `cc::Build::file("c_stubs.cpp")` call still has a valid translation unit.

#include "functional.hpp"
