// validation/c_stubs.cpp — AUTO-GENERATED by xtask regen-registry. DO NOT EDIT.
// Stubs for cc-compile — every non-LDA functional ID needs a fundat_db
// specialisation or xcint.cpp template recursion fails to link.
//
// Phase 3 plan 03-02 removes 17 GGA stubs (PBE×12 + Becke×4 + LYP×1).
// Phase 3 plan 03-03 removes 10 more stubs (OPTX×2 + PW86/91×4 + P86×2 + APBE×2).
// Phase 3 plan 03-04 removes 8 more stubs (B97×6 + KTX + BTK).
// Phase 4 plan 04-01 Wave 1 removes 5 metaGGA stubs (TPSS×3 + revTPSS×2).
// Phase 4 plan 04-01 Task 2 removes 4 more stubs (BRX + BRC + BRXC + CSC).
// Phase 4 plan 04-02 removes 10 SCAN-family stubs (SCAN×2 + rSCAN×2 + r++SCAN×2 + r2SCAN×2 + r4SCAN×2).
// Stubs remaining: 67 - 17 - 10 - 8 - 5 - 4 - 10 = 13.

#include "functional.hpp"

template <typename num> static num stub_unimpl(const densvars<num> &) { return num(0); }

FUNCTIONAL(XC_M05X) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M05X2X) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06X) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06X2X) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06LX) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06HFX) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M05X2C) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M05C) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06C) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06HFC) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06LC) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_M06X2C) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
FUNCTIONAL(XC_BLOCX) = {"stub", "stub", XC_DENSITY|XC_GRADIENT|XC_KINETIC, ENERGY_FUNCTION(stub_unimpl)};
